### ISSUE TITLE
Wrong Payload for A1 series

### ISSUE THREAD

**Issue by mybabysexy** [yeorinhieut/bambu.pages.dev#1]
Current URL: `https://raw.githubusercontent.com/lunDreame/user-bambulab-firmware/main/assets/a1_series_ams.json`
Correct URL: `https://raw.githubusercontent.com/lunDreame/user-bambulab-firmware/main/assets/a1_ams.json`

**Comment by yeorinhieut** [comment]
Fixed!

1e7db44
